// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod rayslash {
    pub mod module {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct QueryContext {
                pub query: _rt::String,
                pub max_results: u32,
                pub locale: Option<_rt::String>,
                pub settings_json: _rt::String,
            }
            impl ::core::fmt::Debug for QueryContext {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("QueryContext")
                        .field("query", &self.query)
                        .field("max-results", &self.max_results)
                        .field("locale", &self.locale)
                        .field("settings-json", &self.settings_json)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum Icon {
                PackagePath(_rt::String),
                Text(_rt::String),
                None,
            }
            impl ::core::fmt::Debug for Icon {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Icon::PackagePath(e) => {
                            f.debug_tuple("Icon::PackagePath").field(e).finish()
                        }
                        Icon::Text(e) => f.debug_tuple("Icon::Text").field(e).finish(),
                        Icon::None => f.debug_tuple("Icon::None").finish(),
                    }
                }
            }
            #[derive(Clone)]
            pub enum Action {
                CopyText(_rt::String),
                OpenUrl(_rt::String),
                ShowMessage(_rt::String),
                Notify((_rt::String, _rt::String)),
                RunApprovedCommand(_rt::Vec<_rt::String>),
                None,
            }
            impl ::core::fmt::Debug for Action {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Action::CopyText(e) => {
                            f.debug_tuple("Action::CopyText").field(e).finish()
                        }
                        Action::OpenUrl(e) => {
                            f.debug_tuple("Action::OpenUrl").field(e).finish()
                        }
                        Action::ShowMessage(e) => {
                            f.debug_tuple("Action::ShowMessage").field(e).finish()
                        }
                        Action::Notify(e) => {
                            f.debug_tuple("Action::Notify").field(e).finish()
                        }
                        Action::RunApprovedCommand(e) => {
                            f.debug_tuple("Action::RunApprovedCommand").field(e).finish()
                        }
                        Action::None => f.debug_tuple("Action::None").finish(),
                    }
                }
            }
            #[derive(Clone)]
            pub struct ResultItem {
                pub id: _rt::String,
                pub title: _rt::String,
                pub subtitle: _rt::String,
                pub icon: Icon,
                pub score: Option<u32>,
                pub action: Action,
            }
            impl ::core::fmt::Debug for ResultItem {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ResultItem")
                        .field("id", &self.id)
                        .field("title", &self.title)
                        .field("subtitle", &self.subtitle)
                        .field("icon", &self.icon)
                        .field("score", &self.score)
                        .field("action", &self.action)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct QueryResponse {
                pub results: _rt::Vec<ResultItem>,
                pub exclusive: bool,
            }
            impl ::core::fmt::Debug for QueryResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("QueryResponse")
                        .field("results", &self.results)
                        .field("exclusive", &self.exclusive)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum ModuleError {
                InvalidQuery(_rt::String),
                Unavailable(_rt::String),
                Internal(_rt::String),
            }
            impl ::core::fmt::Debug for ModuleError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ModuleError::InvalidQuery(e) => {
                            f.debug_tuple("ModuleError::InvalidQuery").field(e).finish()
                        }
                        ModuleError::Unavailable(e) => {
                            f.debug_tuple("ModuleError::Unavailable").field(e).finish()
                        }
                        ModuleError::Internal(e) => {
                            f.debug_tuple("ModuleError::Internal").field(e).finish()
                        }
                    }
                }
            }
            impl ::core::fmt::Display for ModuleError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for ModuleError {}
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type ModuleError = super::super::super::rayslash::module::types::ModuleError;
            #[derive(Clone)]
            pub struct HttpRequest {
                pub method: _rt::String,
                pub url: _rt::String,
                pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                pub body: _rt::Vec<u8>,
            }
            impl ::core::fmt::Debug for HttpRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("HttpRequest")
                        .field("method", &self.method)
                        .field("url", &self.url)
                        .field("headers", &self.headers)
                        .field("body", &self.body)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct HttpResponse {
                pub status: u16,
                pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                pub body: _rt::Vec<u8>,
            }
            impl ::core::fmt::Debug for HttpResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("HttpResponse")
                        .field("status", &self.status)
                        .field("headers", &self.headers)
                        .field("body", &self.body)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn request(request: &HttpRequest) -> Result<HttpResponse, ModuleError> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 6 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 6
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let HttpRequest {
                        method: method0,
                        url: url0,
                        headers: headers0,
                        body: body0,
                    } = request;
                    let vec1 = method0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = url0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let vec6 = headers0;
                    let len6 = vec6.len();
                    let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec6.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result6 = if layout6.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout6);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec6.into_iter().enumerate() {
                        let base = result6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t3_0, t3_1) = e;
                            let vec4 = t3_0;
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = t3_1;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    }
                    let vec7 = body0;
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    let ptr8 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "rayslash:module/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "request"]
                        fn wit_import9(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import9(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import9(
                            ptr1.cast_mut(),
                            len1,
                            ptr2.cast_mut(),
                            len2,
                            result6,
                            len6,
                            ptr7.cast_mut(),
                            len7,
                            ptr8,
                        )
                    };
                    let l10 = i32::from(*ptr8.add(0).cast::<u8>());
                    let result35 = match l10 {
                        0 => {
                            let e = {
                                let l11 = i32::from(
                                    *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u16>(),
                                );
                                let l12 = *ptr8
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l13 = *ptr8
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base20 = l12;
                                let len20 = l13;
                                let mut result20 = _rt::Vec::with_capacity(len20);
                                for i in 0..len20 {
                                    let base = base20
                                        .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                    let e20 = {
                                        let l14 = *base.add(0).cast::<*mut u8>();
                                        let l15 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len16 = l15;
                                        let bytes16 = _rt::Vec::from_raw_parts(
                                            l14.cast(),
                                            len16,
                                            len16,
                                        );
                                        let l17 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l18 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len19 = l18;
                                        let bytes19 = _rt::Vec::from_raw_parts(
                                            l17.cast(),
                                            len19,
                                            len19,
                                        );
                                        (_rt::string_lift(bytes16), _rt::string_lift(bytes19))
                                    };
                                    result20.push(e20);
                                }
                                _rt::cabi_dealloc(
                                    base20,
                                    len20 * (4 * ::core::mem::size_of::<*const u8>()),
                                    ::core::mem::size_of::<*const u8>(),
                                );
                                let l21 = *ptr8
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l22 = *ptr8
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len23 = l22;
                                HttpResponse {
                                    status: l11 as u16,
                                    headers: result20,
                                    body: _rt::Vec::from_raw_parts(l21.cast(), len23, len23),
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l24 = i32::from(
                                    *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                use super::super::super::rayslash::module::types::ModuleError as V34;
                                let v34 = match l24 {
                                    0 => {
                                        let e34 = {
                                            let l25 = *ptr8
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l26 = *ptr8
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len27 = l26;
                                            let bytes27 = _rt::Vec::from_raw_parts(
                                                l25.cast(),
                                                len27,
                                                len27,
                                            );
                                            _rt::string_lift(bytes27)
                                        };
                                        V34::InvalidQuery(e34)
                                    }
                                    1 => {
                                        let e34 = {
                                            let l28 = *ptr8
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l29 = *ptr8
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len30 = l29;
                                            let bytes30 = _rt::Vec::from_raw_parts(
                                                l28.cast(),
                                                len30,
                                                len30,
                                            );
                                            _rt::string_lift(bytes30)
                                        };
                                        V34::Unavailable(e34)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 2, "invalid enum discriminant");
                                        let e34 = {
                                            let l31 = *ptr8
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l32 = *ptr8
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len33 = l32;
                                            let bytes33 = _rt::Vec::from_raw_parts(
                                                l31.cast(),
                                                len33,
                                                len33,
                                            );
                                            _rt::string_lift(bytes33)
                                        };
                                        V34::Internal(e34)
                                    }
                                };
                                v34
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout6.size() != 0 {
                        _rt::alloc::dealloc(result6.cast(), layout6);
                    }
                    result35
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn cache_get(key: &str) -> Result<Option<_rt::Vec<u8>>, ModuleError> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 4
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "rayslash:module/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "cache-get"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result19 = match l3 {
                        0 => {
                            let e = {
                                let l4 = i32::from(
                                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l4 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l5 = *ptr1
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l6 = *ptr1
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len7 = l6;
                                            _rt::Vec::from_raw_parts(l5.cast(), len7, len7)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l8 = i32::from(
                                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                use super::super::super::rayslash::module::types::ModuleError as V18;
                                let v18 = match l8 {
                                    0 => {
                                        let e18 = {
                                            let l9 = *ptr1
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l10 = *ptr1
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len11 = l10;
                                            let bytes11 = _rt::Vec::from_raw_parts(
                                                l9.cast(),
                                                len11,
                                                len11,
                                            );
                                            _rt::string_lift(bytes11)
                                        };
                                        V18::InvalidQuery(e18)
                                    }
                                    1 => {
                                        let e18 = {
                                            let l12 = *ptr1
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l13 = *ptr1
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len14 = l13;
                                            let bytes14 = _rt::Vec::from_raw_parts(
                                                l12.cast(),
                                                len14,
                                                len14,
                                            );
                                            _rt::string_lift(bytes14)
                                        };
                                        V18::Unavailable(e18)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 2, "invalid enum discriminant");
                                        let e18 = {
                                            let l15 = *ptr1
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l16 = *ptr1
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len17 = l16;
                                            let bytes17 = _rt::Vec::from_raw_parts(
                                                l15.cast(),
                                                len17,
                                                len17,
                                            );
                                            _rt::string_lift(bytes17)
                                        };
                                        V18::Internal(e18)
                                    }
                                };
                                v18
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result19
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn cache_put(key: &str, value: &[u8]) -> Result<(), ModuleError> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 4
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = value;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "rayslash:module/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "cache-put"]
                        fn wit_import3(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2)
                    };
                    let l4 = i32::from(*ptr2.add(0).cast::<u8>());
                    let result16 = match l4 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l5 = i32::from(
                                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                use super::super::super::rayslash::module::types::ModuleError as V15;
                                let v15 = match l5 {
                                    0 => {
                                        let e15 = {
                                            let l6 = *ptr2
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l7 = *ptr2
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len8 = l7;
                                            let bytes8 = _rt::Vec::from_raw_parts(
                                                l6.cast(),
                                                len8,
                                                len8,
                                            );
                                            _rt::string_lift(bytes8)
                                        };
                                        V15::InvalidQuery(e15)
                                    }
                                    1 => {
                                        let e15 = {
                                            let l9 = *ptr2
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l10 = *ptr2
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len11 = l10;
                                            let bytes11 = _rt::Vec::from_raw_parts(
                                                l9.cast(),
                                                len11,
                                                len11,
                                            );
                                            _rt::string_lift(bytes11)
                                        };
                                        V15::Unavailable(e15)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 2, "invalid enum discriminant");
                                        let e15 = {
                                            let l12 = *ptr2
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l13 = *ptr2
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len14 = l13;
                                            let bytes14 = _rt::Vec::from_raw_parts(
                                                l12.cast(),
                                                len14,
                                                len14,
                                            );
                                            _rt::string_lift(bytes14)
                                        };
                                        V15::Internal(e15)
                                    }
                                };
                                v15
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result16
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod rayslash {
        pub mod module {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod provider {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ModuleError = super::super::super::super::rayslash::module::types::ModuleError;
                pub type QueryContext = super::super::super::super::rayslash::module::types::QueryContext;
                pub type QueryResponse = super::super::super::super::rayslash::module::types::QueryResponse;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_query_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len2 = arg7;
                    let bytes2 = _rt::Vec::from_raw_parts(arg6.cast(), len2, len2);
                    let result3 = T::query(super::super::super::super::rayslash::module::types::QueryContext {
                        query: _rt::string_lift(bytes0),
                        max_results: arg2 as u32,
                        locale: match arg3 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg5;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg4.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        settings_json: _rt::string_lift(bytes2),
                    });
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result3 {
                        Ok(e) => {
                            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::rayslash::module::types::QueryResponse {
                                results: results5,
                                exclusive: exclusive5,
                            } = e;
                            let vec22 = results5;
                            let len22 = vec22.len();
                            let layout22 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec22.len()
                                    * (8 + 14 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result22 = if layout22.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout22).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout22);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec22.into_iter().enumerate() {
                                let base = result22
                                    .add(i * (8 + 14 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::rayslash::module::types::ResultItem {
                                        id: id6,
                                        title: title6,
                                        subtitle: subtitle6,
                                        icon: icon6,
                                        score: score6,
                                        action: action6,
                                    } = e;
                                    let vec7 = (id6.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *base.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                                    let vec8 = (title6.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                    let vec9 = (subtitle6.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                    use super::super::super::super::rayslash::module::types::Icon as V12;
                                    match icon6 {
                                        V12::PackagePath(e) => {
                                            *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (0i32) as u8;
                                            let vec10 = (e.into_bytes()).into_boxed_slice();
                                            let ptr10 = vec10.as_ptr().cast::<u8>();
                                            let len10 = vec10.len();
                                            ::core::mem::forget(vec10);
                                            *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len10;
                                            *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr10.cast_mut();
                                        }
                                        V12::Text(e) => {
                                            *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (1i32) as u8;
                                            let vec11 = (e.into_bytes()).into_boxed_slice();
                                            let ptr11 = vec11.as_ptr().cast::<u8>();
                                            let len11 = vec11.len();
                                            ::core::mem::forget(vec11);
                                            *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len11;
                                            *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr11.cast_mut();
                                        }
                                        V12::None => {
                                            *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (2i32) as u8;
                                        }
                                    }
                                    match score6 {
                                        Some(e) => {
                                            *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (1i32) as u8;
                                            *base
                                                .add(4 + 9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        None => {
                                            *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (0i32) as u8;
                                        }
                                    };
                                    use super::super::super::super::rayslash::module::types::Action as V21;
                                    match action6 {
                                        V21::CopyText(e) => {
                                            *base
                                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (0i32) as u8;
                                            let vec13 = (e.into_bytes()).into_boxed_slice();
                                            let ptr13 = vec13.as_ptr().cast::<u8>();
                                            let len13 = vec13.len();
                                            ::core::mem::forget(vec13);
                                            *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len13;
                                            *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr13.cast_mut();
                                        }
                                        V21::OpenUrl(e) => {
                                            *base
                                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (1i32) as u8;
                                            let vec14 = (e.into_bytes()).into_boxed_slice();
                                            let ptr14 = vec14.as_ptr().cast::<u8>();
                                            let len14 = vec14.len();
                                            ::core::mem::forget(vec14);
                                            *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len14;
                                            *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr14.cast_mut();
                                        }
                                        V21::ShowMessage(e) => {
                                            *base
                                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (2i32) as u8;
                                            let vec15 = (e.into_bytes()).into_boxed_slice();
                                            let ptr15 = vec15.as_ptr().cast::<u8>();
                                            let len15 = vec15.len();
                                            ::core::mem::forget(vec15);
                                            *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len15;
                                            *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr15.cast_mut();
                                        }
                                        V21::Notify(e) => {
                                            *base
                                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (3i32) as u8;
                                            let (t16_0, t16_1) = e;
                                            let vec17 = (t16_0.into_bytes()).into_boxed_slice();
                                            let ptr17 = vec17.as_ptr().cast::<u8>();
                                            let len17 = vec17.len();
                                            ::core::mem::forget(vec17);
                                            *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len17;
                                            *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr17.cast_mut();
                                            let vec18 = (t16_1.into_bytes()).into_boxed_slice();
                                            let ptr18 = vec18.as_ptr().cast::<u8>();
                                            let len18 = vec18.len();
                                            ::core::mem::forget(vec18);
                                            *base
                                                .add(8 + 13 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len18;
                                            *base
                                                .add(8 + 12 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr18.cast_mut();
                                        }
                                        V21::RunApprovedCommand(e) => {
                                            *base
                                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (4i32) as u8;
                                            let vec20 = e;
                                            let len20 = vec20.len();
                                            let layout20 = _rt::alloc::Layout::from_size_align_unchecked(
                                                vec20.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                            let result20 = if layout20.size() != 0 {
                                                let ptr = _rt::alloc::alloc(layout20).cast::<u8>();
                                                if ptr.is_null() {
                                                    _rt::alloc::handle_alloc_error(layout20);
                                                }
                                                ptr
                                            } else {
                                                ::core::ptr::null_mut()
                                            };
                                            for (i, e) in vec20.into_iter().enumerate() {
                                                let base = result20
                                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let vec19 = (e.into_bytes()).into_boxed_slice();
                                                    let ptr19 = vec19.as_ptr().cast::<u8>();
                                                    let len19 = vec19.len();
                                                    ::core::mem::forget(vec19);
                                                    *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len19;
                                                    *base.add(0).cast::<*mut u8>() = ptr19.cast_mut();
                                                }
                                            }
                                            *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len20;
                                            *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = result20;
                                        }
                                        V21::None => {
                                            *base
                                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (5i32) as u8;
                                        }
                                    }
                                }
                            }
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len22;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result22;
                            *ptr4
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match exclusive5 {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
                            use super::super::super::super::rayslash::module::types::ModuleError as V26;
                            match e {
                                V26::InvalidQuery(e) => {
                                    *ptr4
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec23 = (e.into_bytes()).into_boxed_slice();
                                    let ptr23 = vec23.as_ptr().cast::<u8>();
                                    let len23 = vec23.len();
                                    ::core::mem::forget(vec23);
                                    *ptr4
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len23;
                                    *ptr4
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr23.cast_mut();
                                }
                                V26::Unavailable(e) => {
                                    *ptr4
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec24 = (e.into_bytes()).into_boxed_slice();
                                    let ptr24 = vec24.as_ptr().cast::<u8>();
                                    let len24 = vec24.len();
                                    ::core::mem::forget(vec24);
                                    *ptr4
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len24;
                                    *ptr4
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr24.cast_mut();
                                }
                                V26::Internal(e) => {
                                    *ptr4
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec25 = (e.into_bytes()).into_boxed_slice();
                                    let ptr25 = vec25.as_ptr().cast::<u8>();
                                    let len25 = vec25.len();
                                    ::core::mem::forget(vec25);
                                    *ptr4
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len25;
                                    *ptr4
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr25.cast_mut();
                                }
                            }
                        }
                    };
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_query<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base30 = l1;
                            let len30 = l2;
                            for i in 0..len30 {
                                let base = base30
                                    .add(i * (8 + 14 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = *base.add(0).cast::<*mut u8>();
                                    let l4 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l3, l4, 1);
                                    let l5 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                    let l7 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                    let l9 = i32::from(
                                        *base
                                            .add(6 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    match l9 {
                                        0 => {
                                            let l10 = *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l11 = *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l10, l11, 1);
                                        }
                                        1 => {
                                            let l12 = *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l13 = *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l12, l13, 1);
                                        }
                                        _ => {}
                                    }
                                    let l14 = i32::from(
                                        *base
                                            .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    match l14 {
                                        0 => {
                                            let l15 = *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l16 = *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l15, l16, 1);
                                        }
                                        1 => {
                                            let l17 = *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l18 = *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l17, l18, 1);
                                        }
                                        2 => {
                                            let l19 = *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l20 = *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l19, l20, 1);
                                        }
                                        3 => {
                                            let l21 = *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l22 = *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l21, l22, 1);
                                            let l23 = *base
                                                .add(8 + 12 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l24 = *base
                                                .add(8 + 13 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l23, l24, 1);
                                        }
                                        4 => {
                                            let l25 = *base
                                                .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l26 = *base
                                                .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let base29 = l25;
                                            let len29 = l26;
                                            for i in 0..len29 {
                                                let base = base29
                                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let l27 = *base.add(0).cast::<*mut u8>();
                                                    let l28 = *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l27, l28, 1);
                                                }
                                            }
                                            _rt::cabi_dealloc(
                                                base29,
                                                len29 * (2 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                        }
                                        _ => {}
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base30,
                                len30 * (8 + 14 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l31 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l31 {
                                0 => {
                                    let l32 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l33 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l32, l33, 1);
                                }
                                1 => {
                                    let l34 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l35 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l34, l35, 1);
                                }
                                _ => {
                                    let l36 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l37 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l36, l37, 1);
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    fn query(
                        context: QueryContext,
                    ) -> Result<QueryResponse, ModuleError>;
                }
                #[doc(hidden)]
                macro_rules! __export_rayslash_module_provider_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "rayslash:module/provider@1.0.0#query")] unsafe extern "C" fn
                        export_query(arg0 : * mut u8, arg1 : usize, arg2 : i32, arg3 :
                        i32, arg4 : * mut u8, arg5 : usize, arg6 : * mut u8, arg7 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_query_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5,
                        arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_rayslash:module/provider@1.0.0#query")] unsafe extern
                        "C" fn _post_return_query(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_query::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_rayslash_module_provider_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_module_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::rayslash::module::provider::__export_rayslash_module_provider_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::rayslash::module::provider);
    };
}
#[doc(inline)]
pub(crate) use __export_module_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:rayslash:module@1.0.0:module:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1049] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9c\x07\x01A\x02\x01\
A\x09\x01B\x11\x01ks\x01r\x04\x05querys\x0bmax-resultsy\x06locale\0\x0dsettings-\
jsons\x04\0\x0dquery-context\x03\0\x01\x01q\x03\x0cpackage-path\x01s\0\x04text\x01\
s\0\x04none\0\0\x04\0\x04icon\x03\0\x03\x01o\x02ss\x01ps\x01q\x06\x09copy-text\x01\
s\0\x08open-url\x01s\0\x0cshow-message\x01s\0\x06notify\x01\x05\0\x14run-approve\
d-command\x01\x06\0\x04none\0\0\x04\0\x06action\x03\0\x07\x01ky\x01r\x06\x02ids\x05\
titles\x08subtitles\x04icon\x04\x05score\x09\x06action\x08\x04\0\x0bresult-item\x03\
\0\x0a\x01p\x0b\x01r\x02\x07results\x0c\x09exclusive\x7f\x04\0\x0equery-response\
\x03\0\x0d\x01q\x03\x0dinvalid-query\x01s\0\x0bunavailable\x01s\0\x08internal\x01\
s\0\x04\0\x0cmodule-error\x03\0\x0f\x03\0\x1brayslash:module/types@1.0.0\x05\0\x02\
\x03\0\0\x0cmodule-error\x01B\x13\x02\x03\x02\x01\x01\x04\0\x0cmodule-error\x03\0\
\0\x01o\x02ss\x01p\x02\x01p}\x01r\x04\x06methods\x03urls\x07headers\x03\x04body\x04\
\x04\0\x0chttp-request\x03\0\x05\x01r\x03\x06status{\x07headers\x03\x04body\x04\x04\
\0\x0dhttp-response\x03\0\x07\x01j\x01\x08\x01\x01\x01@\x01\x07request\x06\0\x09\
\x04\0\x07request\x01\x0a\x01k\x04\x01j\x01\x0b\x01\x01\x01@\x01\x03keys\0\x0c\x04\
\0\x09cache-get\x01\x0d\x01j\0\x01\x01\x01@\x02\x03keys\x05value\x04\0\x0e\x04\0\
\x09cache-put\x01\x0f\x03\0\x1arayslash:module/host@1.0.0\x05\x02\x02\x03\0\0\x0d\
query-context\x02\x03\0\0\x0equery-response\x01B\x09\x02\x03\x02\x01\x01\x04\0\x0c\
module-error\x03\0\0\x02\x03\x02\x01\x03\x04\0\x0dquery-context\x03\0\x02\x02\x03\
\x02\x01\x04\x04\0\x0equery-response\x03\0\x04\x01j\x01\x05\x01\x01\x01@\x01\x07\
context\x03\0\x06\x04\0\x05query\x01\x07\x04\0\x1erayslash:module/provider@1.0.0\
\x05\x05\x04\0\x1crayslash:module/module@1.0.0\x04\0\x0b\x0c\x01\0\x06module\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-\
bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
